- hosts: localhost
  become: true
  become_user: root
  tasks:
      - name: Launch the new EC2 Instance
        ec2:
          instance_type: t2.micro
          key_name: GubiMasterKey
          image: ami-0520e698dd500b1d1
          region: us-east-2
          group: sgkupi
          count: 3
          wait: yes
          wait_timeout: 500
          assign_public_ip: yes
          instance_tags:
             name: kupiserver
          monitoring: no
          vpc_subnet_id: subnet-08a0a04fb35f0bd0d
    #  - name: install httpd
    #      name: httpd
    #      state: latest
    ##    service:
      #    name: httpd
      #    state: started
