- hosts: localhost
  tasks:
      - name: Launch the new EC2 Instance
        ec2:
          instance_type: t2.micro
          key_name: GubiMasterKey
          image: ami-0520e698dd500b1d1
          region: us-east-2
          group: sgkupi
          count: 3
          wait: yes
          wait_timeout: 500
          assign_public_ip: yes
          instance_tags:
             name: kupiserver
          monitoring: no
          vpc_subnet_id: subnet-08a0a04fb35f0bd0d

- hosts: localhost
  remote_user: root
  become: True
  tasks:
    - name: Install nginx
      yum:
        name: nginx
        state: present
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
